<?php
// Copyright 2026 J Code
// SPDX-License-Identifier: Apache-2.0
return [
    'currencies' => [
        'dollar'         => ['label' => 'Dollar',            'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/united-states-dollar/'],
        'euro'           => ['label' => 'Euro',              'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/euro/'],
        'pound'          => ['label' => 'Pound',             'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/pound-sterling/'],
        'turkish_lira'   => ['label' => 'Turkish Lira',      'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/turkish-lira/'],
        'uae_dirham'     => ['label' => 'UAE Dirham',        'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/uae-dirham/'],
        'canadian_dollar'=> ['label' => 'Canadian Dollar',   'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/canadian-dollar/'],
        'chinese_yuan'   => ['label' => 'Chinese Yuan',      'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/chinese-yuan/'],
        'indian_rupee'   => ['label' => 'Indian Rupee',      'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/indian-rupee/'],
        'korean_won'     => ['label' => 'South Korean Won',  'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/south-korean-won/'],
        'swiss_franc'    => ['label' => 'Swiss Franc',       'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/swiss-franc/'],
        'japanese_yen'   => ['label' => 'Japanese Yen',      'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/japanese-yen/'],
        'azerbaijani_manat' => ['label' => 'Azerbaijani Manat', 'type' => 'fiat', 'url' => 'https://arzdigital.com/coins/azerbaijani-manat/'],
        'iraqi_dinar'    => ['label' => 'Iraqi Dinar',       'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/iraqi-dinar/'],
        'norwegian_krone'=> ['label' => 'Norwegian Krone',   'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/norwegian-krone/'],
        'russian_ruble'  => ['label' => 'Russian Ruble',     'type' => 'fiat',   'url' => 'https://arzdigital.com/coins/russian-ruble/'],

        'bitcoin'        => ['label' => 'Bitcoin',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/bitcoin/'],
        'ethereum'       => ['label' => 'Ethereum',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/ethereum/'],
        'tether'         => ['label' => 'Tether',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/tether/'],
        'bnb'            => ['label' => 'BNB',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/bnb/'],
        'solana'         => ['label' => 'Solana',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/solana/'],
        'usdc'           => ['label' => 'USD Coin',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/usd-coin/'],
        'xrp'            => ['label' => 'XRP',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/xrp/'],
        'dogecoin'       => ['label' => 'Dogecoin',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/dogecoin/'],
        'toncoin'        => ['label' => 'Toncoin',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/toncoin/'],
        'cardano'        => ['label' => 'Cardano',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/cardano/'],
        'shiba_inu'      => ['label' => 'Shiba Inu',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/shiba-inu/'],
        'avalanche'      => ['label' => 'Avalanche',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/avalanche/'],
        'tron'           => ['label' => 'TRON',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/tron/'],
        'polkadot'       => ['label' => 'Polkadot',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/polkadot-new/'],
        'chainlink'      => ['label' => 'Chainlink',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/chainlink/'],
        'bitcoin_cash'   => ['label' => 'Bitcoin Cash',      'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/bitcoin-cash/'],
        'uniswap'        => ['label' => 'Uniswap',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/uniswap/'],
        'polygon'        => ['label' => 'Polygon',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/polygon/'],
        'litecoin'       => ['label' => 'Litecoin',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/litecoin/'],
        'dai'            => ['label' => 'Dai',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/multi-collateral-dai/'],
        'leo_token'      => ['label' => 'LEO Token',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/unus-sed-leo/'],
        'near'           => ['label' => 'NEAR Protocol',     'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/near-protocol/'],
        'pepe'           => ['label' => 'Pepe',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/pepe/'],
        'icp'            => ['label' => 'Internet Computer', 'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/internet-computer/'],
        'kaspa'          => ['label' => 'Kaspa',             'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/kaspa/'],
        'ethereum_classic'=> ['label' => 'Ethereum Classic', 'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/ethereum-classic/'],
        'monero'         => ['label' => 'Monero',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/monero/'],
        'aptos'          => ['label' => 'Aptos',             'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/aptos/'],
        'render'         => ['label' => 'Render',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/render/'],
        'hedera'         => ['label' => 'Hedera',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/hedera/'],
        'stellar'        => ['label' => 'Stellar',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/stellar/'],
        'mantle'         => ['label' => 'Mantle',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/mantle/'],
        'cosmos'         => ['label' => 'Cosmos',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/cosmos/'],
        'okb'            => ['label' => 'OKB',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/okb/'],
        'cronos'         => ['label' => 'Cronos',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/cronos/'],
        'filecoin'       => ['label' => 'Filecoin',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/filecoin/'],
        'fdusd'          => ['label' => 'First Digital USD', 'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/first-digital-usd/'],
        'stacks'         => ['label' => 'Stacks',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/stacks/'],
        'arbitrum'       => ['label' => 'Arbitrum',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/arbitrum/'],
        'imx'            => ['label' => 'Immutable X',       'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/immutable-x/'],
        'maker'          => ['label' => 'Maker',             'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/maker/'],
        'wif'            => ['label' => 'dogwifhat',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/dogwifhat/'],
        'bittensor'      => ['label' => 'Bittensor',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/bittensor/'],
        'optimism'       => ['label' => 'Optimism',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/optimism-ethereum/'],
        'lido_dao'       => ['label' => 'Lido DAO',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/lido-dao/'],
        'sui'            => ['label' => 'Sui',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/sui/'],
        'the_graph'      => ['label' => 'The Graph',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/the-graph/'],
        'injective'      => ['label' => 'Injective',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/injective/'],
        'vechain'        => ['label' => 'VeChain',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/vechain/'],
        'arweave'        => ['label' => 'Arweave',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/arweave/'],

        'ton'            => ['label' => 'TON Token',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/tontoken/'],
        'gram'           => ['label' => 'Gram (TON)',        'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/toncoin/'],
        'link'           => ['label' => 'LINK',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/chainlink/'],

        'aave'           => ['label' => 'Aave',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/aave/'],
        'algorand'       => ['label' => 'Algorand',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/algorand/'],
        'eos'            => ['label' => 'EOS',               'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/eos/'],
        'theta'          => ['label' => 'Theta Network',     'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/theta-network/'],
        'flow'           => ['label' => 'Flow',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/flow/'],
        'chiliz'         => ['label' => 'Chiliz',            'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/chiliz/'],
        'axie_infinity'  => ['label' => 'Axie Infinity',     'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/axie-infinity/'],
        'apecoin'        => ['label' => 'ApeCoin',           'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/apecoin/'],
        'curve_dao'      => ['label' => 'Curve DAO Token',   'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/curve-dao-token/'],
        'gala'           => ['label' => 'Gala',              'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/gala/'],
        'floki'          => ['label' => 'Floki',             'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/floki-inu/'],
        'decentraland'   => ['label' => 'Decentraland',      'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/decentraland/'],
        'sandbox'        => ['label' => 'The Sandbox',       'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/the-sandbox/'],
        'worldcoin'      => ['label' => 'Worldcoin',         'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/worldcoin/'],
        'celestia'       => ['label' => 'Celestia',          'type' => 'crypto', 'url' => 'https://arzdigital.com/coins/celestia/'],
    ],

    'paths' => [
        'base'   => __DIR__,
        'charts' => __DIR__ . '/charts',
        'data'   => __DIR__ . '/data',
        'locks'  => __DIR__ . '/locks',
        'fonts'  => __DIR__ . '/fonts',
        'icons'  => __DIR__ . '/icons',
    ],

    'allow_dynamic_currencies' => true,
    'coin_url_pattern'         => 'https://arzdigital.com/coins/%s/',
    'max_dynamic_currencies'   => 500,
    'dynamic_lookup_rate_limit'=> 20,
    'dynamic_lookup_rate_window_seconds' => 60,
    'negative_cache_seconds'   => 600,

    'fixed_host' => null,

    'default_tocurrency' => 'T',
    'toman_rate_source'  => 'kifpool',
    'toman_rate_cache_seconds' => 120,
    'custom_toman_rate'  => null,

    'history_days'     => 7,
    'max_period_days'  => 7,
    'chart_width'   => 2000,
    'chart_height'  => 1120,
    'candle_count'  => 48,

    'chart_ttl_seconds' => 102,

    'refresh_after_seconds' => 100,
    'stale_after_seconds'   => 1800,

    'api_rate_limit'            => 60,
    'api_rate_window_seconds'   => 60,

    'api_all_rate_limit'          => 10,
    'api_all_rate_window_seconds' => 60,

    'lock_wait_ms'          => 1000,
    'first_fetch_wait_ms'   => 15000,

    'max_concurrent_fetches' => 6,
    'fetch_slot_wait_ms'     => 3000,

    'api_cache_seconds'     => 15,

    'fetch_connect_timeout' => 8,
    'fetch_timeout'         => 15,
    'fetch_retries'         => 2,
    'fetch_retry_delay_ms'  => 350,

    'all_endpoint_time_budget_seconds' => 20,
    'max_execution_seconds' => 90,
];